### ISSUE TITLE
Sources?

### ISSUE THREAD

**Issue by Xenthio** [BlackShadow/Half-Life-1-RMF-#2]
where are you obtaining these files?

**Comment by BlackShadow** [comment]
@Xenthio The source is kinda mixed. I'm using Leaked WC VMF's for geometry and texture align. For entities i decompile original Goldsrc maps. I also use some geometry from decompiled Goldsrc maps. I create lighting from scratch. (.RADs) I'm aiming to make the source files most accurate to actual source map.

**Comment by BlackShadow** [comment]
@Xenthio The source is kinda mixed. I'm using Leaked WC VMF's for geometry and texture align. For entities i decompile original Goldsrc maps. I also use some minor geometry from decompiled Goldsrc maps as well. I create lighting from scratch. (.RADs)

**Comment by Xenthio** [comment]
damn, props to you for the effort.
