### ISSUE TITLE
will there be more rmfs?

### ISSUE THREAD

**Issue by Droooga** [BlackShadow/Half-Life-1-RMF-#3]
is there gonna be more rmfs anytime soon like c1a1, c2a5a, c1a3 etc...?

awesome work by the way!

**Comment by BlackShadow** [comment]
> is there gonna be more rmfs anytime soon like c1a1, c2a5a, c1a3 etc...?
> 
> awesome work by the way!

Hey there,

Appricate your interest on project! I'll do every map (HL1 currently). This project goes really slow because i can't really focus on this one and i'm the only one working on the project.

**Comment by Droooga** [comment]
oh, i was thinking about contributing a few vmfs ive imported to goldsrc myself some time ago

**Comment by BlackShadow** [comment]
This project doesn't really use decompiled map sources from "WinBSPC or BSP2MAP"

**Comment by Droooga** [comment]
ive added a lot of rmfs from different sources in my fork (most of them being from gamebanana)
