### ISSUE TITLE
[Question] How you doing the map vmf's?

### ISSUE THREAD

**Issue by BratishkaRUS** [BlackShadow/Half-Life-1-RMF-#4]
I want to fix one of the office maps but WinBSPc is garbage, brushes is way too big so it makes map look like a box, also a lot of missing lights in the map, I'm interested how you fix all the stuff and what should I use?

**Comment by BlackShadow** [comment]
Which map you're trying to fix?

**Comment by BratishkaRUS** [comment]
> Which map you're trying to fix?

c1a2b mostly, because it has some texture issues in ventilation section, and then get to other maps

**Comment by BlackShadow** [comment]
Okay so most of the fixes i do is manually. I create lightning from scratch i compare with original map until it's close enough. i fix Texture alignment also manually. I use Leaked WC sources or Half-Life: Source if map isn't in WC leak.

**Comment by BratishkaRUS** [comment]
I've tried to use WC leak but there was some broken triggers, so yeah, waiting for you to do stuff, I hope you would end as soon as possible

**Comment by BratishkaRUS** [comment]
![image](https://user-images.githubusercontent.com/100530331/163607124-d3ad8f35-db8a-49bc-b922-1333ca40fe66.png)

_I don't know if I'm doing great, but I'm trying to do best, I'm also using that vanilla light compilator that you're mention about, maybe it's going to help me like a little bit?_

**Comment by BlackShadow** [comment]
Yes you need to use original QRAD if you want original Half-Life lights. Make sure to align ents as well.

**Comment by BratishkaRUS** [comment]
Appreciate your trying to help man! Finnaly, I would fix some annoying texture glitches in maps, now at least!
